SUPPLIER_MAPS_V1 = {
    "ISCAR": {
        "P": {
            "TOUGH": {"primary": "IC8250", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC807"}},
            "BALANCED": {"primary": "IC8250", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC808"}},
            "WEAR": {"primary": "IC8150", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
        },
        "M": {
            "TOUGH": {"primary": "IC8250", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC807"}},
            "BALANCED": {"primary": "IC8250", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC808"}},
            "WEAR": {"primary": "IC8150", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
        },
        "K": {
            "TOUGH": {"primary": "IC8250", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC807"}},
            "BALANCED": {"primary": "IC8150", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC808"}},
            "WEAR": {"primary": "IC8150", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
        },
        "N": {
            "TOUGH": {"primary": "IC20", "alt_by_coating": {"CVD": "IC20", "PVD": "IC20"}},
            "BALANCED": {"primary": "IC20", "alt_by_coating": {"CVD": "IC20", "PVD": "IC20"}},
            "WEAR": {"primary": "IC20", "alt_by_coating": {"CVD": "IC20", "PVD": "IC20"}},
        },
        "S": {
            "TOUGH": {"primary": "IC807", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC807"}},
            "BALANCED": {"primary": "IC808", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC808"}},
            "WEAR": {"primary": "IC8150", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
        },
        "H": {
            "TOUGH": {"primary": "IC808", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC808"}},
            "BALANCED": {"primary": "IC806", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
            "WEAR": {"primary": "IC806", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
        },
    },
    "SANDVIK": {
        "P": {
            "TOUGH": {"primary": "GC4425", "alt_by_coating": {"CVD": "GC4425", "PVD": "GC4415"}},
            "BALANCED": {"primary": "GC4425", "alt_by_coating": {"CVD": "GC4425", "PVD": "GC4415"}},
            "WEAR": {"primary": "GC4405", "alt_by_coating": {"CVD": "GC4405", "PVD": "GC4415"}},
        },
        "M": {
            "TOUGH": {"primary": "GC2220", "alt_by_coating": {"CVD": "GC2220", "PVD": "GC1115"}},
            "BALANCED": {"primary": "GC2025", "alt_by_coating": {"CVD": "GC2025", "PVD": "GC1115"}},
            "WEAR": {"primary": "GC2015", "alt_by_coating": {"CVD": "GC2015", "PVD": "GC1115"}},
        },
        "K": {
            "TOUGH": {"primary": "GC3210", "alt_by_coating": {"CVD": "GC3210", "PVD": "GC3115"}},
            "BALANCED": {"primary": "GC3225", "alt_by_coating": {"CVD": "GC3225", "PVD": "GC3115"}},
            "WEAR": {"primary": "GC3210", "alt_by_coating": {"CVD": "GC3210", "PVD": "GC3115"}},
        },
        "N": {
            "TOUGH": {"primary": "H13A", "alt_by_coating": {"CVD": "H13A", "PVD": "H13A"}},
            "BALANCED": {"primary": "H10", "alt_by_coating": {"CVD": "H10", "PVD": "H13A"}},
            "WEAR": {"primary": "H10", "alt_by_coating": {"CVD": "H10", "PVD": "H13A"}},
        },
        "S": {
            "TOUGH": {"primary": "S205", "alt_by_coating": {"CVD": "GC1205", "PVD": "S205"}},
            "BALANCED": {"primary": "GC1205", "alt_by_coating": {"CVD": "GC1205", "PVD": "GC1115"}},
            "WEAR": {"primary": "GC1210", "alt_by_coating": {"CVD": "GC1210", "PVD": "GC1115"}},
        },
        "H": {
            "TOUGH": {"primary": "CB7015", "alt_by_coating": {"CVD": "CB7015", "PVD": "CB7015"}},
            "BALANCED": {"primary": "CB7025", "alt_by_coating": {"CVD": "CB7025", "PVD": "CB7015"}},
            "WEAR": {"primary": "CB7025", "alt_by_coating": {"CVD": "CB7025", "PVD": "CB7015"}},
        },
    },
    "KENNAMETAL": {
        "P": {
            "TOUGH": {"primary": "KCU25B", "alt_by_coating": {"CVD": "KCP25C", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCP25C", "alt_by_coating": {"CVD": "KCP25C", "PVD": "KCU25B"}},
            "WEAR": {"primary": "KCU10B", "alt_by_coating": {"CVD": "KCP25C", "PVD": "KCU10B"}},
        },
        "M": {
            "TOUGH": {"primary": "KCS25B", "alt_by_coating": {"CVD": "KCS25B", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCS15B", "alt_by_coating": {"CVD": "KCS15B", "PVD": "KCU25B"}},
            "WEAR": {"primary": "KCS10B", "alt_by_coating": {"CVD": "KCS10B", "PVD": "KCU10B"}},
        },
        "K": {
            "TOUGH": {"primary": "KCK20B", "alt_by_coating": {"CVD": "KCK20B", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCK20B", "alt_by_coating": {"CVD": "KCK20B", "PVD": "KCU10B"}},
            "WEAR": {"primary": "KCK10B", "alt_by_coating": {"CVD": "KCK10B", "PVD": "KCU10B"}},
        },
        "N": {
            "TOUGH": {"primary": "KCU25B", "alt_by_coating": {"CVD": "KCU25B", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCU10B", "alt_by_coating": {"CVD": "KCU10B", "PVD": "KCU10B"}},
            "WEAR": {"primary": "KCU10B", "alt_by_coating": {"CVD": "KCU10B", "PVD": "KCU10B"}},
        },
        "S": {
            "TOUGH": {"primary": "KCU25B", "alt_by_coating": {"CVD": "KCS25B", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCS15B", "alt_by_coating": {"CVD": "KCS15B", "PVD": "KCU25B"}},
            "WEAR": {"primary": "KCS10B", "alt_by_coating": {"CVD": "KCS10B", "PVD": "KCU10B"}},
        },
        "H": {
            "TOUGH": {"primary": "KCU25B", "alt_by_coating": {"CVD": "KCS25B", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCU10B", "alt_by_coating": {"CVD": "KCS10B", "PVD": "KCU10B"}},
            "WEAR": {"primary": "KCU10B", "alt_by_coating": {"CVD": "KCS10B", "PVD": "KCU10B"}},
        },
    },
    "MSC": {
        # MSC carries multi-brand insert catalogs, so these entries are intentionally ISO-bucket defaults.
        "P": {
            "TOUGH": {"primary": "MSC_ISO_P30", "alt_by_coating": {"CVD": "MSC_ISO_P30", "PVD": "MSC_ISO_P25"}},
            "BALANCED": {"primary": "MSC_ISO_P25", "alt_by_coating": {"CVD": "MSC_ISO_P25", "PVD": "MSC_ISO_P25"}},
            "WEAR": {"primary": "MSC_ISO_P15", "alt_by_coating": {"CVD": "MSC_ISO_P15", "PVD": "MSC_ISO_P20"}},
        },
        "M": {
            "TOUGH": {"primary": "MSC_ISO_M30", "alt_by_coating": {"CVD": "MSC_ISO_M30", "PVD": "MSC_ISO_M25"}},
            "BALANCED": {"primary": "MSC_ISO_M25", "alt_by_coating": {"CVD": "MSC_ISO_M25", "PVD": "MSC_ISO_M20"}},
            "WEAR": {"primary": "MSC_ISO_M15", "alt_by_coating": {"CVD": "MSC_ISO_M15", "PVD": "MSC_ISO_M20"}},
        },
        "K": {
            "TOUGH": {"primary": "MSC_ISO_K30", "alt_by_coating": {"CVD": "MSC_ISO_K30", "PVD": "MSC_ISO_K25"}},
            "BALANCED": {"primary": "MSC_ISO_K25", "alt_by_coating": {"CVD": "MSC_ISO_K25", "PVD": "MSC_ISO_K20"}},
            "WEAR": {"primary": "MSC_ISO_K15", "alt_by_coating": {"CVD": "MSC_ISO_K15", "PVD": "MSC_ISO_K20"}},
        },
        "N": {
            "TOUGH": {"primary": "MSC_ISO_N20", "alt_by_coating": {"CVD": "MSC_ISO_N20", "PVD": "MSC_ISO_N20"}},
            "BALANCED": {"primary": "MSC_ISO_N10", "alt_by_coating": {"CVD": "MSC_ISO_N10", "PVD": "MSC_ISO_N10"}},
            "WEAR": {"primary": "MSC_ISO_N05", "alt_by_coating": {"CVD": "MSC_ISO_N05", "PVD": "MSC_ISO_N10"}},
        },
        "S": {
            "TOUGH": {"primary": "MSC_ISO_S30", "alt_by_coating": {"CVD": "MSC_ISO_S30", "PVD": "MSC_ISO_S25"}},
            "BALANCED": {"primary": "MSC_ISO_S25", "alt_by_coating": {"CVD": "MSC_ISO_S25", "PVD": "MSC_ISO_S20"}},
            "WEAR": {"primary": "MSC_ISO_S15", "alt_by_coating": {"CVD": "MSC_ISO_S15", "PVD": "MSC_ISO_S20"}},
        },
        "H": {
            "TOUGH": {"primary": "MSC_ISO_H20", "alt_by_coating": {"CVD": "MSC_ISO_H20", "PVD": "MSC_ISO_H20"}},
            "BALANCED": {"primary": "MSC_ISO_H15", "alt_by_coating": {"CVD": "MSC_ISO_H15", "PVD": "MSC_ISO_H15"}},
            "WEAR": {"primary": "MSC_ISO_H10", "alt_by_coating": {"CVD": "MSC_ISO_H10", "PVD": "MSC_ISO_H10"}},
        },
    },
}

GRADE_DESCRIPTIONS = {
    "IC8250": "Tough CVD grade for general and less stable turning",
    "IC8150": "Harder, wear-oriented CVD option for stable higher-speed cuts",
    "IC808": "Balanced PVD option for mixed stability conditions",
    "IC807": "Tougher PVD option for unstable or interrupted cuts",
    "IC806": "Wear-side PVD option for stable cuts and finishing",
    "IC20": "Uncoated carbide option often used as a baseline for non-ferrous turning",
    "GC4425": "Strong all-around steel turning grade",
    "GC4415": "Tougher Sandvik option when extra edge security is needed",
    "GC4405": "Wear-oriented steel grade for stable high-productivity cuts",
    "GC2220": "Tough stainless turning option for unstable conditions",
    "GC2025": "Balanced stainless turning option",
    "GC2015": "Wear-side stainless option for stable cuts",
    "GC1115": "PVD Sandvik option for stainless and super-alloy work when lower cutting force and edge security matter.",
    "GC3225": "General cast-iron turning option",
    "GC3210": "Wear-focused cast-iron turning option",
    "GC3115": "PVD-side cast-iron option for mixed stability",
    "H13A": "Tough uncoated option for non-ferrous and gummy alloys",
    "H10": "Wear-side option for non-ferrous turning",
    "S205": "Tough super-alloy turning option",
    "GC1205": "Balanced super-alloy turning grade",
    "GC1210": "Wear-side super-alloy turning grade",
    "CB7015": "CBN option leaning toward interrupted hardened turning",
    "CB7025": "CBN option for hardened finishing and wear life",
    "KCP25C": "Versatile CVD steel grade with solid toughness",
    "KCU25B": "Tough universal PVD grade for mixed conditions",
    "KCU10B": "Harder wear-oriented PVD grade for stable finishing conditions",
    "KCS25B": "Tough stainless/super-alloy Kennametal option",
    "KCS15B": "Balanced stainless/super-alloy Kennametal option",
    "KCS10B": "Wear-side stainless/super-alloy Kennametal option",
    "KCK20B": "Balanced cast-iron option",
    "KCK10B": "Wear-focused cast-iron option",
    "MSC_ISO_P30": "MSC multi-brand ISO P roughing bucket (toughness side)",
    "MSC_ISO_P25": "MSC multi-brand ISO P general-purpose bucket",
    "MSC_ISO_P20": "MSC multi-brand ISO P semi-finishing bucket",
    "MSC_ISO_P15": "MSC multi-brand ISO P finishing bucket",
    "MSC_ISO_M30": "MSC multi-brand ISO M roughing bucket",
    "MSC_ISO_M25": "MSC multi-brand ISO M general-purpose bucket",
    "MSC_ISO_M20": "MSC multi-brand ISO M semi-finishing bucket",
    "MSC_ISO_M15": "MSC multi-brand ISO M finishing bucket",
    "MSC_ISO_K30": "MSC multi-brand ISO K roughing bucket",
    "MSC_ISO_K25": "MSC multi-brand ISO K general-purpose bucket",
    "MSC_ISO_K20": "MSC multi-brand ISO K semi-finishing bucket",
    "MSC_ISO_K15": "MSC multi-brand ISO K finishing bucket",
    "MSC_ISO_N20": "MSC multi-brand ISO N roughing bucket",
    "MSC_ISO_N10": "MSC multi-brand ISO N general-purpose bucket",
    "MSC_ISO_N05": "MSC multi-brand ISO N finishing bucket",
    "MSC_ISO_S30": "MSC multi-brand ISO S roughing bucket",
    "MSC_ISO_S25": "MSC multi-brand ISO S general-purpose bucket",
    "MSC_ISO_S20": "MSC multi-brand ISO S semi-finishing bucket",
    "MSC_ISO_S15": "MSC multi-brand ISO S finishing bucket",
    "MSC_ISO_H20": "MSC multi-brand ISO H roughing bucket",
    "MSC_ISO_H15": "MSC multi-brand ISO H general-purpose bucket",
    "MSC_ISO_H10": "MSC multi-brand ISO H finishing bucket",
}
