SUPPLIER_MAPS_V1 = {
    "ISCAR": {
        "P": {
            "TOUGH": {"primary": "IC8250", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC807"}},
            "BALANCED": {"primary": "IC8250", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC808"}},
            "WEAR": {"primary": "IC8150", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
        },
        "M": {
            "TOUGH": {"primary": "IC8250", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC807"}},
            "BALANCED": {"primary": "IC8250", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC808"}},
            "WEAR": {"primary": "IC8150", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
        },
        "K": {
            "TOUGH": {"primary": "IC8250", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC807"}},
            "BALANCED": {"primary": "IC8150", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC808"}},
            "WEAR": {"primary": "IC8150", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
        },
        "N": {
            "TOUGH": {"primary": "IC20", "alt_by_coating": {"CVD": "IC20", "PVD": "IC20"}},
            "BALANCED": {"primary": "IC20", "alt_by_coating": {"CVD": "IC20", "PVD": "IC20"}},
            "WEAR": {"primary": "IC20", "alt_by_coating": {"CVD": "IC20", "PVD": "IC20"}},
        },
        "S": {
            "TOUGH": {"primary": "IC807", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC807"}},
            "BALANCED": {"primary": "IC808", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC808"}},
            "WEAR": {"primary": "IC8150", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
        },
        "H": {
            "TOUGH": {"primary": "IC808", "alt_by_coating": {"CVD": "IC8250", "PVD": "IC808"}},
            "BALANCED": {"primary": "IC806", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
            "WEAR": {"primary": "IC806", "alt_by_coating": {"CVD": "IC8150", "PVD": "IC806"}},
        },
    },
    "SANDVIK": {
        "P": {
            "TOUGH": {"primary": "GC4235", "alt_by_coating": {"CVD": "GC4235", "PVD": "GC4235"}},
            "BALANCED": {"primary": "GC4225", "alt_by_coating": {"CVD": "GC4225", "PVD": "GC4225"}},
            "WEAR": {"primary": "GC4205", "alt_by_coating": {"CVD": "GC4205", "PVD": "GC4215"}},
        },
        "M": {
            "TOUGH": {"primary": "GC2220", "alt_by_coating": {"CVD": "GC2220", "PVD": "GC2220"}},
            "BALANCED": {"primary": "GC2025", "alt_by_coating": {"CVD": "GC2025", "PVD": "GC2025"}},
            "WEAR": {"primary": "GC2015", "alt_by_coating": {"CVD": "GC2015", "PVD": "GC1115"}},
        },
        "K": {
            "TOUGH": {"primary": "GC3225", "alt_by_coating": {"CVD": "GC3225", "PVD": "GC3225"}},
            "BALANCED": {"primary": "GC3215", "alt_by_coating": {"CVD": "GC3215", "PVD": "GC3215"}},
            "WEAR": {"primary": "GC3210", "alt_by_coating": {"CVD": "GC3210", "PVD": "GC3210"}},
        },
        "N": {
            "TOUGH": {"primary": "H13A", "alt_by_coating": {"CVD": "H13A", "PVD": "H13A"}},
            "BALANCED": {"primary": "H13A", "alt_by_coating": {"CVD": "H13A", "PVD": "H13A"}},
            "WEAR": {"primary": "H10A", "alt_by_coating": {"CVD": "H10A", "PVD": "H10A"}},
        },
        "S": {
            "TOUGH": {"primary": "S05F", "alt_by_coating": {"CVD": "S05F", "PVD": "S05F"}},
            "BALANCED": {"primary": "GC1115", "alt_by_coating": {"CVD": "GC1115", "PVD": "GC1115"}},
            "WEAR": {"primary": "GC1105", "alt_by_coating": {"CVD": "GC1105", "PVD": "GC1115"}},
        },
        "H": {
            "TOUGH": {"primary": "CB7015", "alt_by_coating": {"CVD": "CB7015", "PVD": "CB7015"}},
            "BALANCED": {"primary": "CB7025", "alt_by_coating": {"CVD": "CB7025", "PVD": "CB7015"}},
            "WEAR": {"primary": "CB7015", "alt_by_coating": {"CVD": "CB7015", "PVD": "CB7015"}},
        },
    },
    "KYOCERA": {
        "P": {
            "TOUGH": {"primary": "CA5525", "alt_by_coating": {"CVD": "CA5525", "PVD": "PR1125"}},
            "BALANCED": {"primary": "CA5515", "alt_by_coating": {"CVD": "CA5515", "PVD": "PR1115"}},
            "WEAR": {"primary": "PR1025", "alt_by_coating": {"CVD": "PR1025", "PVD": "PR1025"}},
        },
        "M": {
            "TOUGH": {"primary": "CA6525", "alt_by_coating": {"CVD": "CA6525", "PVD": "CA6525"}},
            "BALANCED": {"primary": "PV7020", "alt_by_coating": {"CVD": "PV7020", "PVD": "PR930"}},
            "WEAR": {"primary": "CA6515", "alt_by_coating": {"CVD": "CA6515", "PVD": "CA6515"}},
        },
        "K": {
            "TOUGH": {"primary": "CA4120", "alt_by_coating": {"CVD": "CA4120", "PVD": "CA4120"}},
            "BALANCED": {"primary": "CA4120", "alt_by_coating": {"CVD": "CA4120", "PVD": "CA4120"}},
            "WEAR": {"primary": "CA4115", "alt_by_coating": {"CVD": "CA4115", "PVD": "CR7015"}},
        },
        "N": {
            "TOUGH": {"primary": "KW10", "alt_by_coating": {"CVD": "KW10", "PVD": "KW10"}},
            "BALANCED": {"primary": "KW10", "alt_by_coating": {"CVD": "KW10", "PVD": "KPD010"}},
            "WEAR": {"primary": "KPD001", "alt_by_coating": {"CVD": "KPD001", "PVD": "KPD001"}},
        },
        "S": {
            "TOUGH": {"primary": "PR660", "alt_by_coating": {"CVD": "PR660", "PVD": "PR660"}},
            "BALANCED": {"primary": "PR905", "alt_by_coating": {"CVD": "PR905", "PVD": "PR905"}},
            "WEAR": {"primary": "PR905", "alt_by_coating": {"CVD": "PR905", "PVD": "PR905"}},
        },
        "H": {
            "TOUGH": {"primary": "KBN510", "alt_by_coating": {"CVD": "KBN510", "PVD": "KBN510"}},
            "BALANCED": {"primary": "KBN25B", "alt_by_coating": {"CVD": "KBN25B", "PVD": "KBN25B"}},
            "WEAR": {"primary": "KBN10B", "alt_by_coating": {"CVD": "KBN10B", "PVD": "KBN10B"}},
        },
    },
    "KENNAMETAL": {
        "P": {
            "TOUGH": {"primary": "KCU25B", "alt_by_coating": {"CVD": "KCP25C", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCP25C", "alt_by_coating": {"CVD": "KCP25C", "PVD": "KCU25B"}},
            "WEAR": {"primary": "KCU10B", "alt_by_coating": {"CVD": "KCP25C", "PVD": "KCU10B"}},
        },
        "M": {
            "TOUGH": {"primary": "KCS25B", "alt_by_coating": {"CVD": "KCS25B", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCS15B", "alt_by_coating": {"CVD": "KCS15B", "PVD": "KCU25B"}},
            "WEAR": {"primary": "KCS10B", "alt_by_coating": {"CVD": "KCS10B", "PVD": "KCU10B"}},
        },
        "K": {
            "TOUGH": {"primary": "KCK20B", "alt_by_coating": {"CVD": "KCK20B", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCK20B", "alt_by_coating": {"CVD": "KCK20B", "PVD": "KCU10B"}},
            "WEAR": {"primary": "KCK10B", "alt_by_coating": {"CVD": "KCK10B", "PVD": "KCU10B"}},
        },
        "N": {
            "TOUGH": {"primary": "KCU25B", "alt_by_coating": {"CVD": "KCU25B", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCU10B", "alt_by_coating": {"CVD": "KCU10B", "PVD": "KCU10B"}},
            "WEAR": {"primary": "KCU10B", "alt_by_coating": {"CVD": "KCU10B", "PVD": "KCU10B"}},
        },
        "S": {
            "TOUGH": {"primary": "KCU25B", "alt_by_coating": {"CVD": "KCS25B", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCS15B", "alt_by_coating": {"CVD": "KCS15B", "PVD": "KCU25B"}},
            "WEAR": {"primary": "KCS10B", "alt_by_coating": {"CVD": "KCS10B", "PVD": "KCU10B"}},
        },
        "H": {
            "TOUGH": {"primary": "KCU25B", "alt_by_coating": {"CVD": "KCS25B", "PVD": "KCU25B"}},
            "BALANCED": {"primary": "KCU10B", "alt_by_coating": {"CVD": "KCS10B", "PVD": "KCU10B"}},
            "WEAR": {"primary": "KCU10B", "alt_by_coating": {"CVD": "KCS10B", "PVD": "KCU10B"}},
        },
    },
    "MSC": {
        # MSC carries multi-brand insert catalogs, so these entries are intentionally ISO-bucket defaults.
        "P": {
            "TOUGH": {"primary": "MSC_ISO_P30", "alt_by_coating": {"CVD": "MSC_ISO_P30", "PVD": "MSC_ISO_P25"}},
            "BALANCED": {"primary": "MSC_ISO_P25", "alt_by_coating": {"CVD": "MSC_ISO_P25", "PVD": "MSC_ISO_P25"}},
            "WEAR": {"primary": "MSC_ISO_P15", "alt_by_coating": {"CVD": "MSC_ISO_P15", "PVD": "MSC_ISO_P20"}},
        },
        "M": {
            "TOUGH": {"primary": "MSC_ISO_M30", "alt_by_coating": {"CVD": "MSC_ISO_M30", "PVD": "MSC_ISO_M25"}},
            "BALANCED": {"primary": "MSC_ISO_M25", "alt_by_coating": {"CVD": "MSC_ISO_M25", "PVD": "MSC_ISO_M20"}},
            "WEAR": {"primary": "MSC_ISO_M15", "alt_by_coating": {"CVD": "MSC_ISO_M15", "PVD": "MSC_ISO_M20"}},
        },
        "K": {
            "TOUGH": {"primary": "MSC_ISO_K30", "alt_by_coating": {"CVD": "MSC_ISO_K30", "PVD": "MSC_ISO_K25"}},
            "BALANCED": {"primary": "MSC_ISO_K25", "alt_by_coating": {"CVD": "MSC_ISO_K25", "PVD": "MSC_ISO_K20"}},
            "WEAR": {"primary": "MSC_ISO_K15", "alt_by_coating": {"CVD": "MSC_ISO_K15", "PVD": "MSC_ISO_K20"}},
        },
        "N": {
            "TOUGH": {"primary": "MSC_ISO_N20", "alt_by_coating": {"CVD": "MSC_ISO_N20", "PVD": "MSC_ISO_N20"}},
            "BALANCED": {"primary": "MSC_ISO_N10", "alt_by_coating": {"CVD": "MSC_ISO_N10", "PVD": "MSC_ISO_N10"}},
            "WEAR": {"primary": "MSC_ISO_N05", "alt_by_coating": {"CVD": "MSC_ISO_N05", "PVD": "MSC_ISO_N10"}},
        },
        "S": {
            "TOUGH": {"primary": "MSC_ISO_S30", "alt_by_coating": {"CVD": "MSC_ISO_S30", "PVD": "MSC_ISO_S25"}},
            "BALANCED": {"primary": "MSC_ISO_S25", "alt_by_coating": {"CVD": "MSC_ISO_S25", "PVD": "MSC_ISO_S20"}},
            "WEAR": {"primary": "MSC_ISO_S15", "alt_by_coating": {"CVD": "MSC_ISO_S15", "PVD": "MSC_ISO_S20"}},
        },
        "H": {
            "TOUGH": {"primary": "MSC_ISO_H20", "alt_by_coating": {"CVD": "MSC_ISO_H20", "PVD": "MSC_ISO_H20"}},
            "BALANCED": {"primary": "MSC_ISO_H15", "alt_by_coating": {"CVD": "MSC_ISO_H15", "PVD": "MSC_ISO_H15"}},
            "WEAR": {"primary": "MSC_ISO_H10", "alt_by_coating": {"CVD": "MSC_ISO_H10", "PVD": "MSC_ISO_H10"}},
        },
    },
}

GRADE_DESCRIPTIONS = {
    "IC8250": "Tough CVD grade for general and less stable turning",
    "IC8150": "Harder, wear-oriented CVD option for stable higher-speed cuts",
    "IC808": "Balanced PVD option for mixed stability conditions",
    "IC807": "Tougher PVD option for unstable or interrupted cuts",
    "IC806": "Wear-side PVD option for stable cuts and finishing",
    "IC20": "Uncoated carbide option often used as a baseline for non-ferrous turning",
    "GC4235": "Tough steel turning grade for heavier or less stable work",
    "GC4225": "Balanced steel turning grade for general-purpose use",
    "GC4215": "Finish-side steel turning grade that still keeps some edge support",
    "GC4205": "Wear-oriented steel grade for stable finishing cuts",
    "GC2220": "Tough stainless turning option for unstable conditions",
    "GC2025": "Balanced stainless turning option",
    "GC2015": "Wear-side stainless option for stable cuts",
    "GC3225": "General cast-iron turning option",
    "GC3210": "Wear-focused cast-iron turning option",
    "H13A": "Tough uncoated option for non-ferrous and gummy alloys",
    "H10A": "Wear-side option for non-ferrous turning",
    "S05F": "Tough super-alloy turning option",
    "GC1105": "Wear-side super-alloy turning grade",
    "CB7015": "CBN option leaning toward interrupted hardened turning",
    "CB7025": "CBN option for hardened finishing and wear life",
    "PR1025": "Wear-oriented Kyocera steel grade for stable finishing work",
    "PR1115": "Balanced Kyocera steel grade for general turning",
    "PR1125": "Tougher Kyocera steel grade for roughing and less stable cuts",
    "CA5515": "Balanced CVD Kyocera steel grade",
    "CA5525": "Tougher CVD Kyocera steel grade for roughing",
    "CA6515": "Wear-side Kyocera stainless grade for stable finishing work",
    "CA6525": "Tough Kyocera stainless grade for rougher cuts",
    "PV7020": "Balanced Kyocera stainless grade",
    "PR930": "Balanced Kyocera stainless/threading grade",
    "CA4115": "Wear-side Kyocera cast-iron grade",
    "CA4120": "Balanced Kyocera cast-iron grade",
    "CR7015": "Cast-iron-focused Kyocera grade for stable cuts",
    "KW10": "General Kyocera non-ferrous turning grade",
    "KPD001": "Wear-side Kyocera non-ferrous grade for finishing",
    "KPD010": "Balanced Kyocera non-ferrous grade",
    "PR660": "Kyocera super-alloy grade for rougher conditions",
    "PR905": "Kyocera super-alloy grade for stable general or finishing work",
    "KBN10B": "Kyocera hardened-turning grade for finishing",
    "KBN25B": "Kyocera hardened-turning grade for general work",
    "KBN510": "Kyocera hardened-turning grade for tougher interrupted cuts",
    "KCP25C": "Versatile CVD steel grade with solid toughness",
    "KCU25B": "Tough universal PVD grade for mixed conditions",
    "KCU10B": "Harder wear-oriented PVD grade for stable finishing conditions",
    "KCS25B": "Tough stainless/super-alloy Kennametal option",
    "KCS15B": "Balanced stainless/super-alloy Kennametal option",
    "KCS10B": "Wear-side stainless/super-alloy Kennametal option",
    "KCK20B": "Balanced cast-iron option",
    "KCK10B": "Wear-focused cast-iron option",
    "MSC_ISO_P30": "MSC multi-brand ISO P roughing bucket (toughness side)",
    "MSC_ISO_P25": "MSC multi-brand ISO P general-purpose bucket",
    "MSC_ISO_P20": "MSC multi-brand ISO P semi-finishing bucket",
    "MSC_ISO_P15": "MSC multi-brand ISO P finishing bucket",
    "MSC_ISO_M30": "MSC multi-brand ISO M roughing bucket",
    "MSC_ISO_M25": "MSC multi-brand ISO M general-purpose bucket",
    "MSC_ISO_M20": "MSC multi-brand ISO M semi-finishing bucket",
    "MSC_ISO_M15": "MSC multi-brand ISO M finishing bucket",
    "MSC_ISO_K30": "MSC multi-brand ISO K roughing bucket",
    "MSC_ISO_K25": "MSC multi-brand ISO K general-purpose bucket",
    "MSC_ISO_K20": "MSC multi-brand ISO K semi-finishing bucket",
    "MSC_ISO_K15": "MSC multi-brand ISO K finishing bucket",
    "MSC_ISO_N20": "MSC multi-brand ISO N roughing bucket",
    "MSC_ISO_N10": "MSC multi-brand ISO N general-purpose bucket",
    "MSC_ISO_N05": "MSC multi-brand ISO N finishing bucket",
    "MSC_ISO_S30": "MSC multi-brand ISO S roughing bucket",
    "MSC_ISO_S25": "MSC multi-brand ISO S general-purpose bucket",
    "MSC_ISO_S20": "MSC multi-brand ISO S semi-finishing bucket",
    "MSC_ISO_S15": "MSC multi-brand ISO S finishing bucket",
    "MSC_ISO_H20": "MSC multi-brand ISO H roughing bucket",
    "MSC_ISO_H15": "MSC multi-brand ISO H general-purpose bucket",
    "MSC_ISO_H10": "MSC multi-brand ISO H finishing bucket",
}
